from __future__ import annotations

import json
import math
from pathlib import Path

import pandas as pd

DEBUG_WATERMARK = "% DEBUG EXPORT -- NOT SCIENTIFIC EVIDENCE"
LATEX_ROW_END = "\\\\"


def _escape(value: object) -> str:
    text = str(value)
    for old, new in (
        ("\\", r"\textbackslash{}"),
        ("_", r"\_"),
        ("%", r"\%"),
        ("&", r"\&"),
        ("#", r"\#"),
    ):
        text = text.replace(old, new)
    return text


def _read_manifest(output: Path) -> dict:
    path = output / "aggregate_manifest.json"
    if not path.exists():
        raise ValueError("aggregate_manifest.json is required for paper export")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("aggregate_manifest.json must contain an object")
    return payload


def _eligibility_failures(manifest: dict) -> list[str]:
    checks = {
        "status_complete": manifest.get("status") == "complete",
        "source_manifests_present": bool(manifest.get("source_manifests_present")),
        "compatible_protocol_hashes": bool(manifest.get("compatible_protocol_hashes")),
        "compatible_runtime_identities": bool(manifest.get("compatible_runtime_identities")),
        "no_block_failures": bool(manifest.get("no_block_failures")),
        "scientific_run": bool(manifest.get("scientific_run")),
        "non_synthetic": not bool(manifest.get("synthetic_backend")),
        "immutable_revisions": bool(manifest.get("immutable_revisions")),
        "confirmatory_tier": str(manifest.get("experiment_tier")) == "confirmatory",
        "minimum_seed_count_met": bool(manifest.get("minimum_seed_count_met")),
        "balanced_canonical": str(manifest.get("reliability_mode"))
        == "balanced_canonical",
        "all_sources_balanced": bool(manifest.get("all_sources_balanced")),
        "canonical_tables_used": bool(manifest.get("canonical_tables_used")),
        "all_primary_rows_numerically_accepted": bool(
            manifest.get("all_primary_rows_numerically_accepted")
        ),
        "balanced_sources_scientifically_accepted": bool(
            manifest.get("all_balanced_sources_scientifically_accepted")
        ),
    }
    return [name for name, passed in checks.items() if not passed]


def _prefix(debug: bool) -> str:
    if debug:
        return DEBUG_WATERMARK + "\n"
    return "% Auto-generated by visible-curvature focused exporter.\n"


def _write(path: Path, body: str, *, debug: bool) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_prefix(debug) + body.rstrip() + "\n", encoding="utf-8")
    return path


def _primary(summary: pd.DataFrame) -> pd.DataFrame:
    frame = summary.copy()
    frame = frame[
        (frame["covariance_moment"].astype(str) == "centered")
        & (frame["assignment"].astype(str) == "observed")
    ]
    frame = frame[(frame["alpha"].astype(float) - 0.25).abs() <= 1.0e-12]
    return frame


def _table_rows(frame: pd.DataFrame, columns: list[tuple[str, str]]) -> list[str]:
    rows: list[str] = []
    for _, row in frame.iterrows():
        cells: list[str] = []
        for key, kind in columns:
            value = row.get(key, "")
            if kind == "number":
                try:
                    number = float(value)
                    cells.append("--" if not math.isfinite(number) else f"{number:.3f}")
                except (TypeError, ValueError):
                    cells.append("--")
            else:
                cells.append(_escape(value))
        rows.append(" & ".join(cells) + " " + LATEX_ROW_END)
    return rows


def export_paper_assets(
    output_dir: str | Path,
    paper_root: str | Path,
    *,
    allow_debug_export: bool = False,
) -> list[Path]:
    output = Path(output_dir)
    paper = Path(paper_root)
    manifest = _read_manifest(output)
    failures = _eligibility_failures(manifest)
    if failures and not allow_debug_export:
        if "no_block_failures" in failures:
            raise ValueError("Aggregate is not eligible: no_block_failures is false")
        if "balanced_canonical" in failures:
            raise ValueError(
                "Aggregate is not eligible for scientific paper export: "
                "reliability_mode must be balanced_canonical"
            )
        raise ValueError(
            "Aggregate is not eligible for scientific paper export: " + ", ".join(failures)
        )
    debug = bool(failures)

    summary = pd.read_csv(output / "paired_seed_summary.csv")
    primary = _primary(summary)
    if primary.empty:
        raise ValueError("No primary centered observed alpha=0.25 rows available for export")

    positive = int((primary["reliable_ordering"] == "positive").sum())
    negative = int((primary["reliable_ordering"] == "negative").sum())
    inconclusive = int((primary["reliable_ordering"] == "inconclusive").sum())
    paths: list[Path] = []
    paths.append(
        _write(
            paper / "network_results_autogen.tex",
            "\n".join(
                [
                    f"\\newcommand{{\\NumFocusedBlocks}}{{{len(primary)}}}",
                    f"\\newcommand{{\\NumReliablePositiveBlocks}}{{{positive}}}",
                    f"\\newcommand{{\\NumReliableNegativeBlocks}}{{{negative}}}",
                    f"\\newcommand{{\\NumInconclusiveBlocks}}{{{inconclusive}}}",
                ]
            ),
            debug=debug,
        )
    )

    block_lines = [
        r"\begin{tabular}{lrrl}",
        r"\toprule",
        "Block & $\\Delta G$ & Seeds & Consensus " + LATEX_ROW_END,
        r"\midrule",
        *_table_rows(
            primary.sort_values("block_name"),
            [
                ("block_name", "text"),
                ("delta_g_median", "number"),
                ("n_seeds", "number"),
                ("reliable_ordering", "text"),
            ],
        ),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    paths.append(
        _write(
            paper / "block_gain_autogen.tex",
            "\n".join(block_lines),
            debug=debug,
        )
    )

    control_specs = [
        ("interventions.csv", "assignment_autogen.tex", ["assignment"], "Assignment"),
        (
            "alpha_sweep.csv",
            "alpha_autogen.tex",
            ["assignment", "alpha"],
            r"Assignment / $\alpha$",
        ),
        (
            "damping_sweep.csv",
            "damping_autogen.tex",
            ["assignment", "damping_coefficient"],
            "Assignment / damping",
        ),
    ]
    for source, destination, group_keys, label in control_specs:
        frame = pd.read_csv(output / source)
        if "balanced_reliable_for_inference" in frame.columns:
            accepted = frame["balanced_reliable_for_inference"]
            if accepted.dtype != bool:
                accepted = accepted.astype(str).str.lower().isin(
                    {"true", "1", "yes"}
                )
            frame = frame[accepted]
        if frame.empty:
            raise ValueError(
                f"No numerically accepted rows available in {source}"
            )
        if source == "damping_sweep.csv" and "sweep_mode" in frame.columns:
            group_keys = ["sweep_mode", *group_keys]
            label = "Mode / " + label
        grouped = frame.groupby(group_keys, as_index=False)["delta_g"].median()
        lines = [
            r"\begin{tabular}{lr}",
            r"\toprule",
            f"{label} & median $\\Delta G$ " + LATEX_ROW_END,
            r"\midrule",
        ]
        for _, row in grouped.iterrows():
            key = " / ".join(_escape(row[name]) for name in group_keys)
            lines.append(f"{key} & {float(row['delta_g']):.3f} " + LATEX_ROW_END)
        lines += [r"\bottomrule", r"\end{tabular}"]
        paths.append(
            _write(paper / destination, "\n".join(lines), debug=debug)
        )
    return paths
